language: elixir
env:
   - ELIXIR_ERL_OPTIONS="+T 9"
elixir:
    - 1.0.0
    - 1.0.5
    - 1.1.1
otp_release:
    - 17.4
matrix:
    include:
        - elixir: 1.2.0
          otp_release: 18.2
sudo: false
script:
      - mix test.all
