language: elixir
env:
   - ELIXIR_ERL_OPTIONS="+T 9"
matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 18.3
    - elixir: 1.5.3
      otp_release: 18.3
    - elixir: 1.6.5
      otp_release: 19.3
    - elixir: 1.7.4
      otp_release: 19.3
    - elixir: 1.8.1
      otp_release: 20.3
    - elixir: 1.8.1
      otp_release: 21.1
sudo: false
script:
      - mix test.all
